### ISSUE TITLE
Clarify the exact position of the under function in comparators

### ISSUE THREAD

**Issue by figuld** [lukas-reineke/cmp-under-comparator#3]
The problem is that now the default comparator list in nvim-cmp looks like this:
```
{
  cmp.config.compare.offset,
  cmp.config.compare.exact,
  cmp.config.compare.score,
  cmp.config.compare.recently_used,
  cmp.config.compare.kind,
  cmp.config.compare.sort_text,
  cmp.config.compare.length,
  cmp.config.compare.order,
}
```
So, I can't figure out where to exactly put `require("cmp-under-comparator").under` to have the best completion exerience.

Here
```
  cmp.config.compare.score,
  require("cmp-under-comparator").under,
  cmp.config.compare.recently_used,
  cmp.config.compare.kind,
```
or
```
  cmp.config.compare.score,
  cmp.config.compare.recently_used,
  cmp.config.compare.locality,
  require("cmp-under-comparator").under,
  cmp.config.compare.kind,
```

Could you clarify it in the README?

**Comment by lukas-reineke** [comment]
Either is fine, it's just personal preference. Choose whatever works better for you.

**Comment by figuld** [comment]
@lukas-reineke, but what's the difference between the two?

**Comment by lukas-reineke** [comment]
It changes the priority of the sorting. If you put `recently_used` or `locality` higher, you will get `_*` results higher up in the completion, if you have recently used them, or they are close to your cursor, respectively.
If you put `under-comparator` higher, they will only move to the top of the other `_*` results.

**Comment by figuld** [comment]
Thanks for the explanation.
